### ISSUE TITLE
Tribes of Ire, Version 1 Roadmap

### ISSUE THREAD

**Issue by adrianthewriter** [ambient-games/tribes-of-ire#1]
Design *Tribes of Ire* version 1

- [x] Plan **core resolution** system
- [x] Plan **traits** for PCs
- [ ] Plan **skills** for PCs

**Comment by adrianthewriter** [comment]
Version 1 planning is now taking place on the [Tribes of Ire, Version 1](https://github.com/ambient-games/tribes-of-ire/projects/1) project page.
